// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fglnhagxonzgqiwfhlss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnbG5oYWd4b256Z3Fpd2ZobHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Mjc2NTIsImV4cCI6MjA3MjUwMzY1Mn0.UQTSXyl-io1uy0fgTh7G92hKk2MRRFpNwTnI5z_QWwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});